CREATE TABLESPACE OFR_TS DATAFILE {{ OFR_TS }}' SIZE 64M AUTOEXTEND ON NEXT 12M MAXSIZE 10240M;
/

CREATE TABLESPACE INSPY_AP_TS DATAFILE '{{ INSPY_AP_TS }}' SIZE 64M AUTOEXTEND ON NEXT 12M MAXSIZE 10240M;
/
 
CREATE TEMPORARY TABLESPACE inspy_ap_TEMP TEMPFILE '{{ inspy_ap_TEMP }}' SIZE 64M AUTOEXTEND ON NEXT 10M MAXSIZE 10240M
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
/ 

CREATE TABLESPACE INSPY_SC_TS DATAFILE '{{ INSPY_SC_TS }}' SIZE 64M AUTOEXTEND ON NEXT 12M MAXSIZE 10240M;
/
 
CREATE TEMPORARY TABLESPACE INSPY_SC_TEMP TEMPFILE '{{ INSPY_SC_TEMP }}' SIZE 64M AUTOEXTEND ON NEXT 10M MAXSIZE 10240M
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
/ 
 
CREATE USER {{ repository_prefix }}_OFR
IDENTIFIED BY {{ sysdba_passwd }}
DEFAULT TABLESPACE OFR_TS
TEMPORARY TABLESPACE inspy_ap_TEMP;
/

GRANT CONTENTSERVER_ROLE TO {{ repository_prefix }}_OFR;
ALTER USER {{ repository_prefix }}_OFR DEFAULT ROLE ALL;
GRANT CREATE TABLE TO {{ repository_prefix }}_OFR;
GRANT CREATE VIEW TO {{ repository_prefix }}_OFR;
GRANT CREATE PROCEDURE TO {{ repository_prefix }}_OFR;
GRANT UNLIMITED TABLESPACE TO {{ repository_prefix }}_OFR;
GRANT SELECT ON SYSTEM.SCHEMA_VERSION_REGISTRY TO {{ repository_prefix }}_OFR;
/

CREATE USER INSPY_AP
IDENTIFIED BY {{ sysdba_passwd }}
DEFAULT TABLESPACE INSPY_AP_TS
TEMPORARY TABLESPACE inspy_ap_TEMP;
/

CREATE USER INSPY_CONFIG
IDENTIFIED BY {{ sysdba_passwd }}
DEFAULT TABLESPACE INSPY_AP_TS
TEMPORARY TABLESPACE inspy_ap_TEMP;
/

CREATE USER INSPY_SC
IDENTIFIED BY {{ sysdba_passwd }}
DEFAULT TABLESPACE INSPY_SC_TS
TEMPORARY TABLESPACE INSPY_SC_TEMP;
/

GRANT CONTENTSERVER_ROLE TO inspy_ap;
ALTER USER inspy_ap DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO inspy_ap;
GRANT SELECT ON SYSTEM.SCHEMA_VERSION_REGISTRY TO inspy_ap;
/

GRANT CONTENTSERVER_ROLE TO inspy_config;
ALTER USER inspy_config DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO inspy_config;
GRANT SELECT ON SYSTEM.SCHEMA_VERSION_REGISTRY TO inspy_config;
/

grant unlimited tablespace to {{ repository_prefix }}_SOAINFRA;
grant unlimited tablespace to {{ repository_prefix }}_CAPTURE;
grant unlimited tablespace to {{ repository_prefix }}_MDS;
grant unlimited tablespace to {{ repository_prefix }}_OCS;
grant unlimited tablespace to {{ repository_prefix }}_OFR;
grant unlimited tablespace to {{ repository_prefix }}_ORASDPM;
grant unlimited tablespace to inspy_ap;
grant unlimited tablespace to inspy_config;
grant unlimited tablespace to inspy_sc;
/

CREATE TABLESPACE FIELD_AUDIT_TS DATAFILE '/u00/oradata/IPMQA/FIELD_AUDIT_TS_01.dbf' SIZE 64M AUTOEXTEND ON NEXT 12M MAXSIZE UNLIMITED;
/ 
 
CREATE TEMPORARY TABLESPACE FIELD_AUDIT_TS_TEMP TEMPFILE '/u00/oradata/IPMQA/field_audit_temp.dbf' SIZE 64M AUTOEXTEND ON NEXT 10M MAXSIZE 10240M
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
/ 

ALTER USER INSPY_AP QUOTA UNLIMITED ON FIELD_AUDIT_TS;
/